### ISSUE TITLE
httpservice.ts的catch永远都会走

### ISSUE THREAD

**Issue by xgzl87** [yanxiaojun617/ionic2_tabs#1]
return this.http.get(url + this.toQueryString(paramObj))
            .toPromise()
            .then(res => {
                console.log("nima"+res)
                this.handleSuccess(res.json())})
            .catch(error => {
                console.log("nimei"+error)
                this.handleError(error)});
这段代码的catch永远都会执行，也就是说上一层的代码永远只能得到catch的值了，

把            .then(res => {
                console.log("nima"+res)
                this.handleSuccess(res.json())})
            .catch(error => {
                console.log("nimei"+error)
                this.handleError(error)});
去掉就执行了

**Comment by yanxiaojun617** [comment]
现在加了拦截器(http://www.jianshu.com/p/4af551ad0901)
也重构了HttpService(http://www.jianshu.com/p/e317e1bb3faf)
