### ISSUE TITLE
定位中的LocationPlugin提示为定义，请问一下LocationPlugin的出处是哪里？

### ISSUE THREAD

**Issue by allenwei123** [yanxiaojun617/ionic2_tabs#13]

**Comment by yanxiaojun617** [comment]
提示未定义,说明你插件没有安装成功.
LocationPlugin插件是封装高德android定位sdk而来的.
https://github.com/yanxiaojun617/ionic2_tabs/blob/master/plugins/com.kit.cordova.amaplocation/www/location.js
