### ISSUE TITLE
HttpService错误不走Log

### ISSUE THREAD

**Issue by GitMr** [yanxiaojun617/ionic2_tabs#15]
![image](https://user-images.githubusercontent.com/13921533/34320068-ef2b1032-e82b-11e7-8eb1-04adb45333b5.png)
为神马请求错误不走Log了，没有任何反应。。

**Comment by GitMr** [comment]
感觉请求没有发出去。。

**Comment by ryancui-** [comment]
这是个内网地址请求会超时吧。

**Comment by GitMr** [comment]
是的，TimieOut Error也不报。。没有任何反应

**Comment by GitMr** [comment]
oh it's my fault
