### ISSUE TITLE
strange problem with the camera in android

### ISSUE THREAD

**Issue by Lanseer** [yanxiaojun617/ionic2_tabs#16]
ionic3 project deployed android(iOS has no problem),  in some page,there is a action to get photo from local photo library, everything goes well, but when open  local photo library, current page disappear and pop ,i do not know what happened, my english not very well,i hope you get the point. below is the part of code.........................................................................................................................................................

service code:
/**
   * 使用cordova-plugin-camera获取照片
   * @param options
   * @returns {Promise<string>}
   */
  getPicture(options: CameraOptions = {}): Promise<string> {
    let ops: CameraOptions = Object.assign({
      sourceType: this.camera.PictureSourceType.CAMERA,//图片来源,CAMERA:拍照,PHOTOLIBRARY:相册
      destinationType: this.camera.DestinationType.DATA_URL,//默认返回base64字符串,DATA_URL:base64   FILE_URI:图片路径
      quality: 60,//图像质量，范围为0 - 100
      allowEdit: false,//选择图片前是否允许编辑
      encodingType: this.camera.EncodingType.PNG,
      targetWidth: 1000,//缩放图像的宽度（像素）
      targetHeight: 1000,//缩放图像的高度（像素）
      saveToPhotoAlbum: false,//是否保存到相册
      correctOrientation: true//设置摄像机拍摄的图像是否为正确的方向
    }, options);
    return new Promise((resolve) => {
      this.camera.getPicture(ops).then((imgData: string) => {
        resolve(imgData);
      }, (err) => {
        err == 20 && this.showToast('没有权限,请在设置中开启权限');
        this.warn('getPicture:' + err)
      });
    });
  };

  /**
   * 通过图库获取照片
   * @param options
   * @return {Promise<string>}
   */
  getPictureByPhotoLibrary(options: CameraOptions = {}): Promise<string> {
    return new Promise((resolve) => {
      this.getPicture(Object.assign({
        sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
        destinationType: this.camera.DestinationType.DATA_URL//DATA_URL: 0 base64字符串, FILE_URI: 1图片路径
      }, options)).then((imgData: string) => {
        resolve(imgData);
      }).catch(err => {
        String(err).indexOf('cancel') != -1 ? this.showToast('取消选择图片', 1500) : this.showToast('获取照片失败');
      });
    });
  };

page code:

takePhotoFromAlbum(){

        if (!this.helperService.isMobile()) {
            alert('not support !');
            return;
        }
        this.helperService.getPictureByPhotoLibrary().then(imgData => {
            console.log('local imgData is:', imgData);
        });
    }

thx in advance!

**Comment by zwq8299174** [comment]
可以写中文么？关注这个项目的都是中文，别装逼兄弟 @Lanseer

**Comment by Lanseer** [comment]
我去，我以为是老外的topic，没仔细看【捂脸】，我简单描述下问题：
ionic 项目，tabs风格，当我从首页present一个page出来，就叫page1吧，然后在page1页面点击按钮选择本地图片，当弹出本地图片的窗口后，page1就消失了并且返回到上一页面，android小米pad上是这样的，iOS  pad上没有出现这种情况

**Comment by zwq8299174** [comment]
@Lanseer 你tabs页面到二级页面是怎么过去的，modal的么还是navCtrl过去的？

**Comment by Lanseer** [comment]
@zwq8299174 ，是这样过去的：
let modal =this.modalCtrl.create(CategoryEditorComponent,{category:null}, { cssClass: 'modal-full' });
modal.onDidDismiss(data => {if(data){this.loadCategory()}});
modal.present();

**Comment by Lanseer** [comment]
@zwq8299174 ，我试着用NavController 的push，还是会返回，真的无语啊

**Comment by yanxiaojun617** [comment]
无法重新你说的情况.这种bug要是有ionic团队早就发现了.你检查你的代码.
你可以把我的项目检出来.把tabs.html中的"我的"tab页放到第一个.然后在真机运行.选择更改头像.看是否能重现你的问题

**Comment by yanxiaojun617** [comment]
无法重新你说的情况.请你检查你的代码.
你可以把我的项目检出来.把tabs.html中的"我的"tab页放到第一个.然后在真机运行.选择更改头像.看是否能重现你的问题

**Comment by Lanseer** [comment]
@yanxiaojun617 ,似乎发现了问题所在，已经解决了，安卓和ionic的页面路由冲突导致的

**Comment by zwq8299174** [comment]
你还用了安卓的原生页面导航？ionic的页面栈其实已经做的非常完善了。 @Lanseer
