### ISSUE TITLE
关于极光推送点击通知消息后 打开APP不弹出 指定页面的几种情况

### ISSUE THREAD

**Issue by 1665270637** [yanxiaojun617/ionic2_tabs#17]
现在有2中情况 都是在this.platform.exitApp() 退出APP的情况下点击推送消息开启APP：
第一种情况：
 this.events.subscribe('click', (res) => {
      this.nav.goToRoot({}).then(() => {//页面返回到根页面,就是app一进来的页面
        let activeVC = this.nav.getActive();
        let tabs = activeVC.instance.tabs;//如果有tab获取tab,没有tab直接push指定页面
        tabs.select(2).then(() => {//其中tab为tab的index
          this.nav.push(NewsDetailPage,content);//跳转到指定页面
        })
      });
    });
执行以上代码后 点击推送来的消息 点击后可以到底指定的页面 但是绑定的返回键全部失效 只有页面的左上角的返回可以用。
第二种情况：
jpushOpenNotification() {
    //当点击极光推送消息跳转到指定页面
    this.events.subscribe('jpush.openNotification', content => {
      let tabs = this.nav.getActiveChildNav();
      let tab = tabs.getSelected();
      let activeVC = tab.getActive();
      // if (activeVC.component == AboutPage) {//如果当前所在页面就是将要跳转到的页面则不处理
      //   return;
      // }
      let activeNav = activeVC.getNav();
      activeNav.popToRoot({}).then(() => {//导航跳到最顶层
        tabs.select(3);//选中第一个tab
        let tab = tabs.getSelected();//获取选中的tab
        let activeVC = tab.getActive();//通过当前选中的tab获取ViewController
        let activeNav = activeVC.getNav();//通过当前视图的ViewController获取的NavController
        activeNav.push(NewsDetailPage,content);//跳转到指定页面
      });
    });
  }
执行了这个函数后 在APP没有缩小打开的情况下 点击推送消息 一切正常。
但是在this.platform.exitApp() 退出APP的情况下点击推送消息后APP开启后未打开指定的页面。
军哥关注你很久了 希望可以得到你的解惑 -。-

**Comment by 1665270637** [comment]
setTimeout(() => {
        let tabs = this.nav.getActiveChildNav(); //返回活动的子导航。
        let tab = tabs.getSelected(); // 返回当前选中的选项卡
        let activeVC = tab.getActive(); // 返回活动页面的视图控制器。
        // if (activeVC.component == AboutPage) {//如果当前所在页面就是将要跳转到的页面则不处理
        //   return;
        // }
        let activeNav = activeVC.getNav();
        activeNav.popToRoot({}).then(() => {//导航跳到最顶层
          tabs.select(3);//选中第一个tab
          let tab = tabs.getSelected();//获取选中的tab
          let activeVC = tab.getActive();//通过当前选中的tab获取ViewController
          let activeNav = activeVC.getNav();//通过当前视图的ViewController获取的NavController
          activeNav.push(NewsDetailPage,content);//跳转到指定页面
        });
      }, 200);

**Comment by 1665270637** [comment]
setTimeout(() => {
        let tabs = this.nav.getActiveChildNav(); //返回活动的子导航。
        let tab = tabs.getSelected(); // 返回当前选中的选项卡
        let activeVC = tab.getActive(); // 返回活动页面的视图控制器。
        // if (activeVC.component == AboutPage) {//如果当前所在页面就是将要跳转到的页面则不处理
        //   return;
        // }
        let activeNav = activeVC.getNav();
        activeNav.popToRoot({}).then(() => {//导航跳到最顶层
          tabs.select(3);//选中第一个tab
          let tab = tabs.getSelected();//获取选中的tab
          let activeVC = tab.getActive();//通过当前选中的tab获取ViewController
          let activeNav = activeVC.getNav();//通过当前视图的ViewController获取的NavController
          activeNav.push(NewsDetailPage,content);//跳转到指定页面
        });
      }, 200);

这样就解决了

**Comment by 1665270637** [comment]
最终我的做法是1、app.component.ts
this.helper.initJpush();//初始化极光推送
this.jpushOpenNotification();//处理打开推送消息事件
jpushOpenNotification() {
    //当点击极光推送消息跳转到指定页面
    this.events.subscribe('jpush.openNotification', content => {
      this.storage.get('LoginInfo').then((loginInfo) => {
        if (loginInfo) {
            let tabs = this.nav.getActiveChildNav(); //返回活动的子导航。
            let tab = tabs.getSelected(); // 返回当前选中的选项卡
            let activeVC = tab.getActive(); // 返回活动页面的视图控制器。
            // if (activeVC.component == AboutPage) {//如果当前所在页面就是将要跳转到的页面则不处理
            //   return;
            // }
            let activeNav = activeVC.getNav();
            activeNav.popToRoot({}).then(() => {//导航跳到最顶层
              tabs.select(3);//选中第一个tab
              let tab = tabs.getSelected();//获取选中的tab
              let activeVC = tab.getActive();//通过当前选中的tab获取ViewController
              let activeNav = activeVC.getNav();//通过当前视图的ViewController获取的NavController
              activeNav.push(NewsDetailPage,content);//跳转到指定页面
            });
        } else {
          this.storage.set('Content', content);
        }
      });
  });
}

2、tabs的第一页面钩子里面放
this.storage.get('Content').then((content)=>{
            if(content){
              this.navCtrl.push(NewsDetailPage,content);
            }
          });

3、指定页面的页面离开钩子里面放
ionViewWillLeave(){
    this.storage.remove('Content');
  }

**Comment by yanxiaojun617** [comment]
你一下发这么多冗余代码看的我晕.
关于你最初说的第一种情况(安卓返回按键失效)问题.已经解决.
请对比你的返回按钮处理方法下面代码.
registerBackButtonAction() {
    if (!this.nativeService.isAndroid()) {
      return;
    }
    this.platform.registerBackButtonAction(() => {
      this.events.publish('android:backButtonAction');
      if (this.keyboard.isOpen()) {//如果键盘开启则隐藏键盘
        this.keyboard.close();
        return;
      }
      //如果想点击返回按钮隐藏toast或loading或Overlay就把下面加上
      // this.ionicApp._toastPortal.getActive() ||this.ionicApp._loadingPortal.getActive()|| this.ionicApp._overlayPortal.getActive()
      let activePortal = this.ionicApp._modalPortal.getActive() || this.ionicApp._toastPortal.getActive() || this.ionicApp._overlayPortal.getActive();
      if (activePortal) {
        activePortal.dismiss();
        return;
      }
      let tabs = this.nav.getActiveChildNav();//获取tabs导航,this.nav是总导航,tabs是子导航
      let tab = tabs.getSelected();//获取选中的tab
      let activeVC = tab.getActive();//通过当前选中的tab获取ViewController
      let activeNav = activeVC.getNav();//通过当前视图的ViewController获取的NavController
      return activeNav.canGoBack() ? activeNav.pop() : this.nativeService.minimize();//this.showExit()
    }, 1);
  }

源码在:https://github.com/yanxiaojun617/ionic2_tabs/blob/master/src/app/app.component.ts
