### ISSUE TITLE
你们试一下这个插件，安装完了是不是打包出错

### ISSUE THREAD

**Issue by zwq8299174** [yanxiaojun617/ionic2_tabs#18]
插件是https://ionicframework.com/docs/native/photo-library/
项目里需要类似有二维码，长按保存到相册。用了官方的这个插件，然后前几天没事儿，可以打包，可以build，今天在学着这个项目弄极光推送的东西，装插件装不上，以为是极光插件的事儿，然后把原版的库git下来以后，直接build也会报错，最终确定删除这个插件就不报错了。下面是报错信息

Failed to restore plugin "cordova-plugin-photo-library" from config.xml. You might need to try adding it again. Error: Error: Cann
ot find module '../cordova/platform_metadata'

**Comment by yanxiaojun617** [comment]
我这里人气没那么火啊，你应该在这里（https://github.com/terikon/cordova-plugin-photo-library）提交你的问题哦。
