### ISSUE TITLE
后台服务器程序

### ISSUE THREAD

**Issue by SeanTaoZH** [yanxiaojun617/ionic2_tabs#19]
大佬能开源下这个程序对应的后台服务器的代码吗，真心想学习一下，万分感谢。

**Comment by yanxiaojun617** [comment]
不好意思,这个后台不是我开发的,算是公司资产.所以不能开源.
此app用到api接口也比较少,目前主要就是登录这里,但是在login.ts中可以看到登录接口的返回数据格式:https://github.com/yanxiaojun617/ionic2_tabs/blob/master/src/pages/login/login.ts

**Comment by SeanTaoZH** [comment]
哦哦，多谢大神解答
