### ISSUE TITLE
ModelController弹出的model按返回键无法关闭 model。但是页面会一直返回。

### ISSUE THREAD

**Issue by huangzk** [yanxiaojun617/ionic2_tabs#2]
你好，视觉上来说modelContrller弹出的实际上也是一个界面，返回键能否监听关闭这个model呢？

**Comment by yanxiaojun617** [comment]
看这里第45行:https://github.com/yanxiaojun617/ionic2_tabs/blob/master/src/app/app.component.ts

也可以去这里:http://www.jianshu.com/p/6aa5a8318092
