### ISSUE TITLE
想问下你项目中myjs.min.js的用途的用法

### ISSUE THREAD

**Issue by zwq8299174** [yanxiaojun617/ionic2_tabs#20]
看到你项目中有字符串加密的一个js：myjs.min.js。想问下这个怎么用，有什么API么，哪些加密是可逆的，哪些是不可逆，在什么情况下用

**Comment by yanxiaojun617** [comment]
这个js就是把一个字符串参数,加密为一个32位的字符串.如:hex_md5('123'); 处理后结果为'202cb962ac59075b964b07152d234b70'
为了不把用户的密码明文传输,它在我项目中的应用就是把用户输入的的密码加密后传到后台
注意:对于后台来说用户的密码就是加密后的32位字符串.所以后台再对用户的密码如何加密如何解密采用什么对称或不对称算法都和myjs.min.js没关系
