### ISSUE TITLE
hello,你好，重写了返回键，弹出的popover界面按返回无法关闭。

### ISSUE THREAD

**Issue by huangzk** [yanxiaojun617/ionic2_tabs#4]
let popover = this.popoverCtrl.create(OmsAlarmFilterPopover, {
            popoverData: this.popoverData
        }, { cssClass: 'fadeInDown' });

        popover.present({
            ev: ev
        });

**Comment by yanxiaojun617** [comment]
看你app.component.ts改成这一句
let activePortal = this.ionicApp._modalPortal.getActive() || this.ionicApp._toastPortal.getActive() || this.ionicApp._loadingPortal.getActive() || this.ionicApp._overlayPortal.getActive();
