### ISSUE TITLE
交流，极光推送的建议这么搞，因为在jpushplugin..init()可能不是一次就成功。

### ISSUE THREAD

**Issue by huangzk** [yanxiaojun617/ionic2_tabs#5]
if (num <= 10) {
            let startTimeStamp = new Date().getTime();
            this.nativeService.initJpush().then(data => {
                this.logService.addLog("getRegistrationID:" + data + ",耗时[ " + ((new Date().getTime() - startTimeStamp) / 1000) + "s ]");
                if (data == null || data.length == 0) {
                    setTimeout(() => {
                        num++;
                        _self.initJpush(num);
                    }, 3000);
                }
            })
        } 
如题：可能registrationId获取多次都为空。设置一个超时操作，重复执行这个过程。之前写法跟你的help一样，线上经常收不到推送，尤其在ios上。原因获取不到registrationId,然后就setAlias，这样是无法绑定别名的哈。

**Comment by yanxiaojun617** [comment]
我在实际测试中还没遇到jpush init不成功.如果后面测试确实有问题,我会改简书和github.
至于你说jPushPlugin.getRegistrationID()获取不到,这个方法我现在没有使用.所以没有过多测试
我的app都是需要用户登录的.所以用setAlias的是userid

**Comment by huangzk** [comment]
是的，但实际上setAlias绑定的就是userId和rergistrationId的关系，判断init成不成功得看registrationid拿不拿得到,后面如果机型多可以再试试就是。

**Comment by yanxiaojun617** [comment]
好的
