### ISSUE TITLE
请教关于多点显示

### ISSUE THREAD

**Issue by tqangxl** [yanxiaojun617/ionic2_tabs#6]
1.能自动显示多点么(几万个标记，如数据库中有几万个个客户)？即自适应显示多个点标记如何做呢？如a,b,c,d,e,f,g,h标记点，a,b,c,d在屏幕内，e,f,g,h不在当前屏幕内，但缩放或移动地图就能看到e,f,g,h标记点

**Comment by tqangxl** [comment]
自适应显示多个点标记如何做呢

**Comment by yanxiaojun617** [comment]
地图同时标记几万个点肯定卡慢.所以使用点聚合.http://lbs.amap.com/api/javascript-api/example/marker/markerclusterer.
