### ISSUE TITLE
请教关于自定义标记点图标显示

### ISSUE THREAD

**Issue by tqangxl** [yanxiaojun617/ionic2_tabs#7]
如a,b,c,d,e,f,g,h标记点，每个标记点有10种或者更多状态，状态图标都在a.png中，根据mongoDB查到的不同状态(已接单，待处理，正在制作，制作完成，正在送餐，已送达，未回访，本周三预约回访，下周预约回访，已回访……)，显示不同图标该怎么弄呢？
http://lbs.amap.com/api/javascript-api/example/marker/custom-icon
谢谢！

**Comment by yanxiaojun617** [comment]
图标图片有两种类型,String、Icon.你这情况就用icon类型..你这url已经给出了答案呀,自己设置大小和偏移量就行了.api看http://lbs.amap.com/api/javascript-api/reference/overlay#Icon
