### ISSUE TITLE
我刚开始接触ionic，我对这个项目有两个问题想请教下，1.项目中使用了模块化结构，这个能起到懒加载的作用么，2.刚进入项目时，切换tab，会有延迟，这个延迟的原因是因为懒加载的原因么，有什么解决办法。

### ISSUE THREAD

**Issue by 1345g2354** [yanxiaojun617/ionic2_tabs#9]

**Comment by yanxiaojun617** [comment]
我这里的*.module.ts没有懒加载效果.只是为了方便开发.懒加载实现看这里http://ionicframework.com/docs/api/navigation/IonicPage/
切换tab延迟这个没感觉到.是不是手机性能导致的.配置低的手机反映是不够流畅
